### PR TITLE
fix #45 and fix #46 by adding pause option and improve cancel handling

### LINKED ISSUE #45: improve option to discard a track
There is currently no way to actually discard a track without saving.

- Press "start"
- select sport e.g. running
- start recording
- press stop
- you now have two options
   - no, keep recording -> obviously no stop
   - yes, stop -> goes to save screen
- in save screen we get two options
   - save -> that would be no discard
   - cancel -> goes back to recording 
- > that last dialog should have three options:
1. save
2. cancel and resume recording
3. cancel and discard track

### LINKED ISSUE #46: [feature request] add option to pause recording
Currently there is no way to pause a recording. It does either run or is stopped and saved. 

Sometimes one may want to pause recording. Say you are jogging along, meet a friend and have a chat. That would mess up your readings.

### LINKED ISSUE #47: give user an info that the screen must not be locked while recording
For the app to work, it either needs to have the screen turned on all the time (no screen locking!) or background suspension needs to be enabled. I can not find any in-app info for the user about this. Only one short line in the [README](https://github.com/ernesst/ActivityTracker/blob/master/README.md?plain=1#L44).

There should be a info dialog maybe (first run? or every time when recording?) or some other way to make the user aware of this.

### PR DESCRIPTION
**Pull request by Danfro**
Only merge after #44  !

This PR **based on focal branch** does address two issues:
1. it will add an option to pause recording (#46 )
2. it will improve cancel/discard track handling (#45 )

I will mark it as draft for now so we can discuss the UI and wait for the focal PR to get merged.

We can not (easily) fully omit bottom edge's "down arrow". So my idea was that the down arrow will become a "start/pause" button. (screenshot 1, 2, 3) Using it for pause/resume actually feels quite convenient in real use. 

The "start" header button does the same as pressing the square green "start" button (yes, redundant).
The "pause" button will pause the recording and change to "start" to allow resume.

The dialog popping up when pressing the red square "stop" button I changed to hold 4 buttons:
a) stop and save recording (as before)
b) stop and discard recording (moved here from header down arrow)
c) pause (new)
d) do nothing, go back (as before)
There are two colored buttons in that menu. That somehow seems to make sense. Although I am aware that this violates the OS UI guidelines. But many current dialogs do that too actually.
Also we could remove pause from this menu and only have it in the header. But I think handling with the larger buttons is better when you are doing some sports rather than aiming for the small header icon. I would keep both options.

Screenshots 1, 2, 3 start/resume/pause:

grafik

grafik

grafik

Screenshots 4, 5, 6 new menu layout (menu with pause, menu with resume, cancel and discard dialog):

grafik

grafik

grafik

### CODE REVIEW

**Comment by mymike00** [comment]
Mmh I don't really like all this redundancy... I see most popular apps on android have a big button (like we have) to start and pause the activity, but when it is paused the buttons become two: one to resume and the other to save. I think that would be doable, there's no issue with small button like the top one and we keep the dialog more understandable with less options

**Comment by Danfro** [comment]
So you suggest to split the red stop button into two? 
- one for stop -> display dialog (stop+save|stop+discard|return)
- one for pause/resume

And somehow either have no button at all in the header (not sure how to trick bottom edge into that) or maybe just show an icon without any functionality?
There could be the `location` icon maybe if we can't fully omit it.

**Comment by mymike00** [comment]
Yes, exactly. And the green button wouldn't be split.
For the header idk, because if you want to go back before starting the activity the arrow is still needed. Could be hidden or disabled once the tracking starts but yeah, we'd have to look how easy overriding it is

**Comment by Danfro** [comment]
Hmm. You are right. I entirely missed that option to go back while not having started yet. Ok, true that is a valid action in the header.

**Comment by Danfro** [comment]
Ok, regarding the header icon, I decided it works best to have:
- down arrow as icon all the time
- enabled when no new activity has been started + allow cancel action there
- disabled in all other situations (paused or recording)

**Comment by Danfro** [comment]
The stop button I did split in half and make it resume and stop. This would look like this now (recording state, paused state, dialog):

grafik

grafik

grafik

**Comment by mymike00** [comment]
Oh, I was imagining the pause/stop buttons aligned in a row so that they can have roughly the same size as the single button or a little bit less, but this could work too

**Comment by Danfro** [comment]
I don't think having the buttons narrower that this is a good idea. Some translations will be longer that the English words. Thats why I stacked them on top of each other. 

For translations, I am actually not sure if we should make the buttons wider.

**Comment by Danfro** [comment]
The buttons start/stop/resume actually have no width set. So they would increase in width for longer translations. 

Not sure if setting a fixed width would be better. But button does not allow elide for text I think. So it would need to be wide enough for all sensible translations.

**Comment by Danfro** [comment]
With a fixed width of `units.gu(16) it would look like this. I actually like it. We could also use a ratio here. This is a bit less than 1/3 of the full width.

grafik

grafik

**Comment by Danfro** [comment]
I swapped the save activity dialog buttons since it feels more natural to have save on the right hand side. Also I did remove the red color on the cancel button since dialogs should only have one colored button and save seems to be the main (desired) action here.

grafik

**Comment by Danfro** [comment]
So now this should be really ready to go. :innocent: If you agree on setting the button width...

After this is merged, we need to update the .pot file. I would do that in another PR.

**Comment by Danfro** [comment]
Actually with the two buttons pause and stop being both visible at the same time, we may need to set a fixed width. Otherwise with translated words being different length, we end up with buttons having a different width. Here for testing with clickable desktop just made Pause longer.

grafik

**Comment by Danfro** [comment]
As a possible solution, we could maybe:
- set the width to a ratio of the full width, like 2/5 of the full -> this should reduce scaling issues
- set the width conditionally according to the text length: width = 2/5 or text.length if wider than 2/5

**Comment by Danfro** [comment]
I did spend some time using the app while on holiday and had some new ideas how to fix the buttons and encountered a few more (old) issues.

A newly discovered issue is, that the buttons are not horizontally aligned centered. So they can move left or right depending on the text column content. But that can be fixed by using a RowLayout and aligning them center.

Also I found my above suggestion with the vertical split stop button for stop/pause is hard to handle while on the move. How about a "floating" pause button above the bottom row? It only takes up a small part of the map and will disappear when it is paused but only be visible when recording?

I am also suggesting a solution to #53 . Why not extend the bottom bar in height a bit? The copyright note is visible due to the transparency but we still have the nice design.

Please see screenshots below:

grafik

grafik

@mymike00 would those solutions be fine with you to finalize this MR? Then I would push the code as well.

**Comment by Danfro** [comment]
Ah, and with the Layout we can set a prefered width for the buttons. That ensures a decent minimum width but also allows the button to stretch a bit when a translation is a bit longer.

**Comment by Danfro** [comment]
Ok, I just pushed the latest code. Screenshots of the buttons below. @mymike00  or @ernesst I would really like to get this finished. Also it would be great to see ActivityTracker in OpenStore for focal.

The start/stop button has 1/3 of the available width as size now. That matches the pause button on my devices. If the translated content gets too long, it will elide...

grafik

grafik

**Comment by Danfro** [comment]
Closing this PR here. I will include it in the now developed fork under https://github.com/Danfro/ActivityTracker.

**Pull request closed without merging**
