### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by SanderKlootwijk**

### CODE REVIEW

**Comment by mymike00** [comment]
I appreciate your translation but we're managing languages stuff with [weblate](https://hosted.weblate.org/projects/activity-tracker/translations/), please start a new translation [there](https://hosted.weblate.org/new-lang/activity-tracker/translations/)
also we're about to publish a new version of the app with all new translations, we can wait for your one on weblate before publishing if you want
thanks

**Comment by ernesst** [comment]
@SanderKlootwijk  Any update regarding Weblate ?

Thanks

**Comment by SanderKlootwijk** [comment]
I completely forgot about this...
But the translations are now uploaded to Weblate :D

I’ll close this pull request!

**Comment by mymike00** [comment]
👍🏻

**Pull request closed without merging**
