### PR TITLE
Update French and remove incorrect `fr_AG` language code

### PR DESCRIPTION
**Pull request by NathanBnm**
This language code does not exist. You have to use `fr` instead.
As the most recent translation were in the `fr_AG.po` file I moved them into the `fr.po` file.

Don't forget to remove it from Weblate (https://hosted.weblate.org/languages/fr_AG/activity-tracker/).

### CODE REVIEW

**Comment by mymike00** [comment]
> As the most recent translation were in the fr_AG.po file I moved them into the fr.po file.

I see both translation on weblate at 100%, so I suppose `fr.po` is up to date too, isn't it?

**Comment by NathanBnm** [comment]
No it wasn't because the `fr.po` file wasn't updated.

**Comment by mymike00** [comment]
I will check, because recently I added new string so someone translated those string in the `fr.po`, otherwise it wouldn't be 100%...

**Comment by NathanBnm** [comment]
@mymike00 the translator of the `fr_AG.po` file is the same than the `fr.po` file and he last updated the `fr_AG.po` file instead of the `fr.po` file. (The `PO-Revision-Date` was more recent).

**Comment by NathanBnm** [comment]
But it seems that your translation files are not up to date. Because they don't all have the same strings in the same order.

**Comment by ernesst** [comment]
Yes somehow your translation file is from 03/19, instead the latest one is from 08 or 10/19.

**Comment by NathanBnm** [comment]
Is your `pot` file up to date? I'm gonna check then.

**Comment by mymike00** [comment]
I just checked your file with the one from weblate and they are more or less the same, some strings are translated in a slightly different way.
In addition on weblate are present some more strings that aren't in your `.po` so I suggest you to just edit translations on weblate if you don't like some of them...

**Comment by ernesst** [comment]
J'ai regarde les phrases incompletes, comme le mentionne @mymike00, edit Weblate si besoin.
Merci.

**Comment by NathanBnm** [comment]
@mymike00 I checked the `fr` translation on Weblate. Now it's fine and up to date. You can safely remove the `fr_AG` translation which is now depracated!

**Pull request closed without merging**
